---
- name: Setup Apigee Hybrid
  hosts: all
  environment:
    USE_GKE_GCLOUD_AUTH_PLUGIN: "true"
    HELM_EXPERIMENTAL_OCI: "1"
  roles:
  - role: cert-manager
    tags:
    - cert-manager

  - role: certificates
    tags:
    - certs

  - role: prepare-helm
    tags:
    - prepare-helm

  - role: prepare-service-accounts
    tags:
    - prepare-service-accounts

  - role: enable-apigee-synchronizer
    tags:
    - enable-synchronizer

  - role: bootstrap-apigee-crds
    tags:
    - bootstrap-apigee-crds

  - role: apigee-hybrid-overrides
    tags:
    - generate-overrides

  - role: helm-ops
    release_name: 'operator'
    chart_ref: 'apigee-operator'
    release_namespace: 'apigee-system'
    create_namespace: true
    tags:
    - ao

  - role: helm-ops
    release_name: 'datastore'
    chart_ref: 'apigee-datastore'
    release_namespace: 'apigee'
    create_namespace: false
    tags:
    - ds
    - apigeeds

  - role: helm-ops
    release_name: 'telemetry'
    chart_ref: 'apigee-telemetry'
    release_namespace: 'apigee'
    create_namespace: false
    tags:
    - at
    - apigeetelem

  - role: helm-ops
    release_name: 'redis'
    chart_ref: 'apigee-redis'
    release_namespace: 'apigee'
    create_namespace: false
    tags:
    - apigeeredis

  - role: helm-ops
    release_name: 'ingress-manager'
    chart_ref: 'apigee-ingress-manager'
    release_namespace: 'apigee'
    create_namespace: false
    tags:
    - apigeeingress

  - role: helm-ops
    release_name: '{{ overrides.gcp.projectID }}'
    chart_ref: 'apigee-org'
    release_namespace: 'apigee'
    create_namespace: false
    tags:
    - apigeeorg
    - apigeeorgs

  tasks:
  - name: deploy environment
    include_role:
      name: helm-ops
      apply:
        tags: apigeeenv
    vars:
      release_name: "{{ item.name }}"
      chart_ref: 'apigee-env'
      release_namespace: 'apigee'
      create_namespace: false
      custom_values: true
      set_values: 
      - value: "env={{ item.name }}"
        value_type: string
    loop: "{{ overrides.envs }}"
    tags:
    - apigeeenv

  - name: deploy environment-group
    include_role:
      name: helm-ops
      apply:
        tags: apigee-virtualhost
    vars:
      release_name: "{{ item.name }}"
      chart_ref: 'apigee-virtualhost'
      release_namespace: 'apigee'
      create_namespace: false
      custom_values: true
      set_values: 
      - value: "envgroup={{ item.name }}"
        value_type: string
    loop: "{{ overrides.virtualhosts }}"
    tags:
    - apigee-virtualhost

  - name: validate-api-calls
    include_role:
      name: validate-api-calls
      apply:
        tags: validate
    tags:
    - validate
