# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Static Checks Pipeline
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run Mega Linter
        uses: oxsecurity/megalinter@v9
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_GHERKIN: false
          VALIDATE_JSCPD: false
          SPELL_MISSPELL_DISABLE_ERRORS: true
          SPELL_CSPELL_DISABLE_ERRORS: true
          COPYPASTE_JSCPD_DISABLE_ERRORS: true
          LINTER_RULES_PATH: "."
          GROOVY_NPM_GROOVY_LINT_FILTER_REGEX_EXCLUDE: "Jenkinsfile"
          MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
          PYTHON_MYPY_DISABLE_ERRORS: true
          PYTHON_BANDIT_DISABLE_ERRORS: true
          DISABLE_LINTERS: PYTHON_PYRIGHT,PYTHON_PYLINT,TERRAFORM_TFLINT,REPOSITORY_KICS,YAML_V8R
          TERRAFORM_TERRASCAN_FILE_EXTENSIONS: .tf
          TERRAFORM_TERRASCAN_ARGUMENTS: -d /github/workspace/test/terraform/control-plane
          SPELL_LYCHEE_DISABLE_ERRORS: true
          REPOSITORY_TRIVY_DISABLE_ERRORS: true
          REPOSITORY_CHECKOV_DISABLE_ERRORS: true
          REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
          TERRAFORM_TERRASCAN_DISABLE_ERRORS: true
          REPOSITORY_GRYPE_DISABLE_ERRORS: true

  commit-messages:
    name: Conventional Commits Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/config/commitlint.config.js
          failOnWarnings: false
